window.GALOK_POSTCARDS = Object.freeze([
  {
    "id": "xiamen-arrival-lines",
    "title": "Arrival Lines",
    "technique": "Photo Abstract Editorial",
    "city": "xiamen",
    "cityLabel": "Xiamen",
    "cityDisplay": "XIAMEN",
    "code": "XM",
    "coordinates": "24.4798° N / 118.0894° E",
    "image": "/assets/editorial/xiamen/postcard/arrival-lines.webp",
    "thumb": "/assets/editorial/xiamen/postcard/thumb/arrival-lines.webp",
    "color": "#554032"
  },
  {
    "id": "xiamen-island-city",
    "title": "Island / City",
    "technique": "Photo Abstract Editorial",
    "city": "xiamen",
    "cityLabel": "Xiamen",
    "cityDisplay": "XIAMEN",
    "code": "XM",
    "coordinates": "24.4798° N / 118.0894° E",
    "image": "/assets/editorial/xiamen/postcard/island-city.webp",
    "thumb": "/assets/editorial/xiamen/postcard/thumb/island-city.webp",
    "color": "#8d3c35"
  },
  {
    "id": "xiamen-wall-still-speaks",
    "title": "Wall Still Speaks",
    "technique": "Minimal Zine Edition",
    "city": "xiamen",
    "cityLabel": "Xiamen",
    "cityDisplay": "XIAMEN",
    "code": "XM",
    "coordinates": "24.4798° N / 118.0894° E",
    "image": "/assets/editorial/xiamen/postcard/wall-still-speaks.webp",
    "thumb": "/assets/editorial/xiamen/postcard/thumb/wall-still-speaks.webp",
    "color": "#4E2724"
  },
  {
    "id": "xiamen-sea-holds-light",
    "title": "Sea Holds Light",
    "technique": "Minimal Zine Edition",
    "city": "xiamen",
    "cityLabel": "Xiamen",
    "cityDisplay": "XIAMEN",
    "code": "XM",
    "coordinates": "24.4798° N / 118.0894° E",
    "image": "/assets/editorial/xiamen/postcard/sea-holds-light.webp",
    "thumb": "/assets/editorial/xiamen/postcard/thumb/sea-holds-light.webp",
    "color": "#92735B"
  },
  {
    "id": "xiamen-sea-evening",
    "title": "Sea Evening",
    "technique": "Photo Abstract Editorial",
    "city": "xiamen",
    "cityLabel": "Xiamen",
    "cityDisplay": "XIAMEN",
    "code": "XM",
    "coordinates": "24.4798° N / 118.0894° E",
    "image": "/assets/editorial/xiamen/postcard/sea-evening.webp",
    "thumb": "/assets/editorial/xiamen/postcard/thumb/sea-evening.webp",
    "color": "#6B97C7"
  },
  {
    "id": "xiamen-gulangyu-roofs",
    "title": "Gulangyu Roofs",
    "technique": "Minimal Zine Edition",
    "city": "xiamen",
    "cityLabel": "Xiamen",
    "cityDisplay": "XIAMEN",
    "code": "XM",
    "coordinates": "24.4798° N / 118.0894° E",
    "image": "/assets/editorial/xiamen/postcard/gulangyu-roofs.webp",
    "thumb": "/assets/editorial/xiamen/postcard/thumb/gulangyu-roofs.webp",
    "color": "#223A46"
  },
  {
    "id": "xiamen-university-road",
    "title": "University Road",
    "technique": "Photo Abstract Editorial",
    "city": "xiamen",
    "cityLabel": "Xiamen",
    "cityDisplay": "XIAMEN",
    "code": "XM",
    "coordinates": "24.4798° N / 118.0894° E",
    "image": "/assets/editorial/xiamen/postcard/university-road.webp",
    "thumb": "/assets/editorial/xiamen/postcard/thumb/university-road.webp",
    "color": "#418844"
  },
  {
    "id": "xiamen-temple-detail",
    "title": "Temple Detail",
    "technique": "Minimal Zine Edition",
    "city": "xiamen",
    "cityLabel": "Xiamen",
    "cityDisplay": "XIAMEN",
    "code": "XM",
    "coordinates": "24.4798° N / 118.0894° E",
    "image": "/assets/editorial/xiamen/postcard/temple-detail.webp",
    "thumb": "/assets/editorial/xiamen/postcard/thumb/temple-detail.webp",
    "color": "#26364A"
  },
  {
    "id": "xiamen-coast-at-16-42",
    "title": "Coast at 16:42",
    "technique": "Photo Abstract Editorial",
    "city": "xiamen",
    "cityLabel": "Xiamen",
    "cityDisplay": "XIAMEN",
    "code": "XM",
    "coordinates": "24.4798° N / 118.0894° E",
    "image": "/assets/editorial/xiamen/postcard/coast-at-16-42.webp",
    "thumb": "/assets/editorial/xiamen/postcard/thumb/coast-at-16-42.webp",
    "color": "#3577A8"
  },
  {
    "id": "xiamen-ferry-west",
    "title": "Ferry / West",
    "technique": "Minimal Zine Edition",
    "city": "xiamen",
    "cityLabel": "Xiamen",
    "cityDisplay": "XIAMEN",
    "code": "XM",
    "coordinates": "24.4798° N / 118.0894° E",
    "image": "/assets/editorial/xiamen/postcard/ferry-west.webp",
    "thumb": "/assets/editorial/xiamen/postcard/thumb/ferry-west.webp",
    "color": "#1D434D"
  },
  {
    "id": "xiamen-last-light-offshore",
    "title": "Last Light Offshore",
    "technique": "Photo Abstract Editorial",
    "city": "xiamen",
    "cityLabel": "Xiamen",
    "cityDisplay": "XIAMEN",
    "code": "XM",
    "coordinates": "24.4798° N / 118.0894° E",
    "image": "/assets/editorial/xiamen/postcard/last-light-offshore.webp",
    "thumb": "/assets/editorial/xiamen/postcard/thumb/last-light-offshore.webp",
    "color": "#223350"
  },
  {
    "id": "xiamen-blue-city-red-lights",
    "title": "Blue City / Red Lights",
    "technique": "Minimal Zine Edition",
    "city": "xiamen",
    "cityLabel": "Xiamen",
    "cityDisplay": "XIAMEN",
    "code": "XM",
    "coordinates": "24.4798° N / 118.0894° E",
    "image": "/assets/editorial/xiamen/postcard/blue-city-red-lights.webp",
    "thumb": "/assets/editorial/xiamen/postcard/thumb/blue-city-red-lights.webp",
    "color": "#23394C"
  },
  {
    "id": "xiamen-temple-sky",
    "title": "Temple Sky",
    "technique": "Photo Abstract Editorial",
    "city": "xiamen",
    "cityLabel": "Xiamen",
    "cityDisplay": "XIAMEN",
    "code": "XM",
    "coordinates": "24.4798° N / 118.0894° E",
    "image": "/assets/editorial/xiamen/postcard/temple-sky.webp",
    "thumb": "/assets/editorial/xiamen/postcard/thumb/temple-sky.webp",
    "color": "#5E2721"
  },
  {
    "id": "xiamen-skyline-under-cloud",
    "title": "Skyline Under Cloud",
    "technique": "Minimal Zine Edition",
    "city": "xiamen",
    "cityLabel": "Xiamen",
    "cityDisplay": "XIAMEN",
    "code": "XM",
    "coordinates": "24.4798° N / 118.0894° E",
    "image": "/assets/editorial/xiamen/postcard/skyline-under-cloud.webp",
    "thumb": "/assets/editorial/xiamen/postcard/thumb/skyline-under-cloud.webp",
    "color": "#2B505E"
  },
  {
    "id": "xiamen-open-water",
    "title": "Open Water",
    "technique": "Photo Abstract Editorial",
    "city": "xiamen",
    "cityLabel": "Xiamen",
    "cityDisplay": "XIAMEN",
    "code": "XM",
    "coordinates": "24.4798° N / 118.0894° E",
    "image": "/assets/editorial/xiamen/postcard/open-water.webp",
    "thumb": "/assets/editorial/xiamen/postcard/thumb/open-water.webp",
    "color": "#1F4E71"
  },
  {
    "id": "xiamen-island-coast",
    "title": "Island Coast",
    "technique": "Minimal Zine Edition",
    "city": "xiamen",
    "cityLabel": "Xiamen",
    "cityDisplay": "XIAMEN",
    "code": "XM",
    "coordinates": "24.4798° N / 118.0894° E",
    "image": "/assets/editorial/xiamen/postcard/island-coast.webp",
    "thumb": "/assets/editorial/xiamen/postcard/thumb/island-coast.webp",
    "color": "#9F7A61"
  },
  {
    "id": "xiamen-coastal-skyline",
    "title": "Coastal Skyline",
    "technique": "Photo Abstract Editorial",
    "city": "xiamen",
    "cityLabel": "Xiamen",
    "cityDisplay": "XIAMEN",
    "code": "XM",
    "coordinates": "24.4798° N / 118.0894° E",
    "image": "/assets/editorial/xiamen/postcard/coastal-skyline.webp",
    "thumb": "/assets/editorial/xiamen/postcard/thumb/coastal-skyline.webp",
    "color": "#C3AB79"
  },
  {
    "id": "xiamen-between-two-signs",
    "title": "Between Two Signs",
    "technique": "Minimal Zine Edition",
    "city": "xiamen",
    "cityLabel": "Xiamen",
    "cityDisplay": "XIAMEN",
    "code": "XM",
    "coordinates": "24.4798° N / 118.0894° E",
    "image": "/assets/editorial/xiamen/postcard/between-two-signs.webp",
    "thumb": "/assets/editorial/xiamen/postcard/thumb/between-two-signs.webp",
    "color": "#95572F"
  },
  {
    "id": "xiamen-xiamen-wall",
    "title": "Xiamen / Wall",
    "technique": "Photo Abstract Editorial",
    "city": "xiamen",
    "cityLabel": "Xiamen",
    "cityDisplay": "XIAMEN",
    "code": "XM",
    "coordinates": "24.4798° N / 118.0894° E",
    "image": "/assets/editorial/xiamen/postcard/xiamen-wall.webp",
    "thumb": "/assets/editorial/xiamen/postcard/thumb/xiamen-wall.webp",
    "color": "#8d3c35"
  },
  {
    "id": "xiamen-street-under-heat",
    "title": "Street Under Heat",
    "technique": "Minimal Zine Edition",
    "city": "xiamen",
    "cityLabel": "Xiamen",
    "cityDisplay": "XIAMEN",
    "code": "XM",
    "coordinates": "24.4798° N / 118.0894° E",
    "image": "/assets/editorial/xiamen/postcard/street-under-heat.webp",
    "thumb": "/assets/editorial/xiamen/postcard/thumb/street-under-heat.webp",
    "color": "#4C3921"
  },
  {
    "id": "xiamen-zhongshan-road",
    "title": "Zhongshan Road",
    "technique": "Photo Abstract Editorial",
    "city": "xiamen",
    "cityLabel": "Xiamen",
    "cityDisplay": "XIAMEN",
    "code": "XM",
    "coordinates": "24.4798° N / 118.0894° E",
    "image": "/assets/editorial/xiamen/postcard/zhongshan-road.webp",
    "thumb": "/assets/editorial/xiamen/postcard/thumb/zhongshan-road.webp",
    "color": "#048803"
  },
  {
    "id": "xiamen-blue-hour-road",
    "title": "Blue Hour Road",
    "technique": "Minimal Zine Edition",
    "city": "xiamen",
    "cityLabel": "Xiamen",
    "cityDisplay": "XIAMEN",
    "code": "XM",
    "coordinates": "24.4798° N / 118.0894° E",
    "image": "/assets/editorial/xiamen/postcard/blue-hour-road.webp",
    "thumb": "/assets/editorial/xiamen/postcard/thumb/blue-hour-road.webp",
    "color": "#243943"
  },
  {
    "id": "xiamen-tunnel-cycle",
    "title": "Tunnel Cycle",
    "technique": "Photo Abstract Editorial",
    "city": "xiamen",
    "cityLabel": "Xiamen",
    "cityDisplay": "XIAMEN",
    "code": "XM",
    "coordinates": "24.4798° N / 118.0894° E",
    "image": "/assets/editorial/xiamen/postcard/tunnel-cycle.webp",
    "thumb": "/assets/editorial/xiamen/postcard/thumb/tunnel-cycle.webp",
    "color": "#7A8B58"
  },
  {
    "id": "xiamen-xiamen-university",
    "title": "Xiamen University",
    "technique": "Minimal Zine Edition",
    "city": "xiamen",
    "cityLabel": "Xiamen",
    "cityDisplay": "XIAMEN",
    "code": "XM",
    "coordinates": "24.4798° N / 118.0894° E",
    "image": "/assets/editorial/xiamen/postcard/xiamen-university.webp",
    "thumb": "/assets/editorial/xiamen/postcard/thumb/xiamen-university.webp",
    "color": "#4C3628"
  },
  {
    "id": "xiamen-oyster-omelette",
    "title": "Oyster Omelette",
    "technique": "Photo Abstract Editorial",
    "city": "xiamen",
    "cityLabel": "Xiamen",
    "cityDisplay": "XIAMEN",
    "code": "XM",
    "coordinates": "24.4798° N / 118.0894° E",
    "image": "/assets/editorial/xiamen/postcard/oyster-omelette.webp",
    "thumb": "/assets/editorial/xiamen/postcard/thumb/oyster-omelette.webp",
    "color": "#635220"
  },
  {
    "id": "xiamen-city-inside-bay",
    "title": "City Inside Bay",
    "technique": "Minimal Zine Edition",
    "city": "xiamen",
    "cityLabel": "Xiamen",
    "cityDisplay": "XIAMEN",
    "code": "XM",
    "coordinates": "24.4798° N / 118.0894° E",
    "image": "/assets/editorial/xiamen/postcard/city-inside-bay.webp",
    "thumb": "/assets/editorial/xiamen/postcard/thumb/city-inside-bay.webp",
    "color": "#0779C2"
  },
  {
    "id": "xiamen-bridge-to-the-coast",
    "title": "Bridge to the Coast",
    "technique": "Photo Abstract Editorial",
    "city": "xiamen",
    "cityLabel": "Xiamen",
    "cityDisplay": "XIAMEN",
    "code": "XM",
    "coordinates": "24.4798° N / 118.0894° E",
    "image": "/assets/editorial/xiamen/postcard/bridge-to-the-coast.webp",
    "thumb": "/assets/editorial/xiamen/postcard/thumb/bridge-to-the-coast.webp",
    "color": "#2C5257"
  },
  {
    "id": "xiamen-pier-at-dusk",
    "title": "Pier at Dusk",
    "technique": "Minimal Zine Edition",
    "city": "xiamen",
    "cityLabel": "Xiamen",
    "cityDisplay": "XIAMEN",
    "code": "XM",
    "coordinates": "24.4798° N / 118.0894° E",
    "image": "/assets/editorial/xiamen/postcard/pier-at-dusk.webp",
    "thumb": "/assets/editorial/xiamen/postcard/thumb/pier-at-dusk.webp",
    "color": "#253351"
  },
  {
    "id": "xian-wall-as-horizon",
    "title": "Wall as Horizon",
    "technique": "Photo Abstract Editorial",
    "city": "xian",
    "cityLabel": "Xi’an",
    "cityDisplay": "XI'AN",
    "code": "XA",
    "coordinates": "34.3416° N / 108.9398° E",
    "image": "/assets/editorial/xian/postcard/wall-as-horizon.webp",
    "thumb": "/assets/editorial/xian/postcard/thumb/wall-as-horizon.webp",
    "color": "#0EA3DC"
  },
  {
    "id": "xian-bell-after-blue",
    "title": "Bell After Blue",
    "technique": "Minimal Zine Edition",
    "city": "xian",
    "cityLabel": "Xi’an",
    "cityDisplay": "XI'AN",
    "code": "XA",
    "coordinates": "34.3416° N / 108.9398° E",
    "image": "/assets/editorial/xian/postcard/bell-after-blue.webp",
    "thumb": "/assets/editorial/xian/postcard/thumb/bell-after-blue.webp",
    "color": "#3B6394"
  },
  {
    "id": "xian-earth-keeps-ranks",
    "title": "Earth Keeps Ranks",
    "technique": "Photo Abstract Editorial",
    "city": "xian",
    "cityLabel": "Xi’an",
    "cityDisplay": "XI'AN",
    "code": "XA",
    "coordinates": "34.3416° N / 108.9398° E",
    "image": "/assets/editorial/xian/postcard/earth-keeps-ranks.webp",
    "thumb": "/assets/editorial/xian/postcard/thumb/earth-keeps-ranks.webp",
    "color": "#463A2C"
  },
  {
    "id": "xian-painted-sky",
    "title": "Painted Sky",
    "technique": "Minimal Zine Edition",
    "city": "xian",
    "cityLabel": "Xi’an",
    "cityDisplay": "XI'AN",
    "code": "XA",
    "coordinates": "34.3416° N / 108.9398° E",
    "image": "/assets/editorial/xian/postcard/painted-sky.webp",
    "thumb": "/assets/editorial/xian/postcard/thumb/painted-sky.webp",
    "color": "#8D2126"
  },
  {
    "id": "xian-city-wall-sunset",
    "title": "City Wall Sunset",
    "technique": "Photo Abstract Editorial",
    "city": "xian",
    "cityLabel": "Xi’an",
    "cityDisplay": "XI'AN",
    "code": "XA",
    "coordinates": "34.3416° N / 108.9398° E",
    "image": "/assets/editorial/xian/postcard/city-wall-sunset.webp",
    "thumb": "/assets/editorial/xian/postcard/thumb/city-wall-sunset.webp",
    "color": "#C58D71"
  },
  {
    "id": "xian-arrival-threshold",
    "title": "Arrival Threshold",
    "technique": "Minimal Zine Edition",
    "city": "xian",
    "cityLabel": "Xi’an",
    "cityDisplay": "XI'AN",
    "code": "XA",
    "coordinates": "34.3416° N / 108.9398° E",
    "image": "/assets/editorial/xian/postcard/arrival-threshold.webp",
    "thumb": "/assets/editorial/xian/postcard/thumb/arrival-threshold.webp",
    "color": "#483B2B"
  },
  {
    "id": "xian-imperial-gate",
    "title": "Imperial Gate",
    "technique": "Photo Abstract Editorial",
    "city": "xian",
    "cityLabel": "Xi’an",
    "cityDisplay": "XI'AN",
    "code": "XA",
    "coordinates": "34.3416° N / 108.9398° E",
    "image": "/assets/editorial/xian/postcard/imperial-gate.webp",
    "thumb": "/assets/editorial/xian/postcard/thumb/imperial-gate.webp",
    "color": "#5C2F1D"
  },
  {
    "id": "xian-terracotta-portrait",
    "title": "Terracotta Portrait",
    "technique": "Minimal Zine Edition",
    "city": "xian",
    "cityLabel": "Xi’an",
    "cityDisplay": "XI'AN",
    "code": "XA",
    "coordinates": "34.3416° N / 108.9398° E",
    "image": "/assets/editorial/xian/postcard/terracotta-portrait.webp",
    "thumb": "/assets/editorial/xian/postcard/thumb/terracotta-portrait.webp",
    "color": "#8b342c"
  },
  {
    "id": "xian-painted-procession",
    "title": "Painted Procession",
    "technique": "Photo Abstract Editorial",
    "city": "xian",
    "cityLabel": "Xi’an",
    "cityDisplay": "XI'AN",
    "code": "XA",
    "coordinates": "34.3416° N / 108.9398° E",
    "image": "/assets/editorial/xian/postcard/painted-procession.webp",
    "thumb": "/assets/editorial/xian/postcard/thumb/painted-procession.webp",
    "color": "#5F3A25"
  },
  {
    "id": "xian-bronze-procession",
    "title": "Bronze Procession",
    "technique": "Minimal Zine Edition",
    "city": "xian",
    "cityLabel": "Xi’an",
    "cityDisplay": "XI'AN",
    "code": "XA",
    "coordinates": "34.3416° N / 108.9398° E",
    "image": "/assets/editorial/xian/postcard/bronze-procession.webp",
    "thumb": "/assets/editorial/xian/postcard/thumb/bronze-procession.webp",
    "color": "#8b342c"
  },
  {
    "id": "xian-museum-curtain-light",
    "title": "Museum Curtain Light",
    "technique": "Photo Abstract Editorial",
    "city": "xian",
    "cityLabel": "Xi’an",
    "cityDisplay": "XI'AN",
    "code": "XA",
    "coordinates": "34.3416° N / 108.9398° E",
    "image": "/assets/editorial/xian/postcard/museum-curtain-light.webp",
    "thumb": "/assets/editorial/xian/postcard/thumb/museum-curtain-light.webp",
    "color": "#614222"
  },
  {
    "id": "xian-shrine-in-shadow",
    "title": "Shrine in Shadow",
    "technique": "Minimal Zine Edition",
    "city": "xian",
    "cityLabel": "Xi’an",
    "cityDisplay": "XI'AN",
    "code": "XA",
    "coordinates": "34.3416° N / 108.9398° E",
    "image": "/assets/editorial/xian/postcard/shrine-in-shadow.webp",
    "thumb": "/assets/editorial/xian/postcard/thumb/shrine-in-shadow.webp",
    "color": "#48392C"
  },
  {
    "id": "xian-standing-figure",
    "title": "Standing Figure",
    "technique": "Photo Abstract Editorial",
    "city": "xian",
    "cityLabel": "Xi’an",
    "cityDisplay": "XI'AN",
    "code": "XA",
    "coordinates": "34.3416° N / 108.9398° E",
    "image": "/assets/editorial/xian/postcard/standing-figure.webp",
    "thumb": "/assets/editorial/xian/postcard/thumb/standing-figure.webp",
    "color": "#8b342c"
  },
  {
    "id": "xian-cloud-pattern",
    "title": "Cloud Pattern",
    "technique": "Minimal Zine Edition",
    "city": "xian",
    "cityLabel": "Xi’an",
    "cityDisplay": "XI'AN",
    "code": "XA",
    "coordinates": "34.3416° N / 108.9398° E",
    "image": "/assets/editorial/xian/postcard/cloud-pattern.webp",
    "thumb": "/assets/editorial/xian/postcard/thumb/cloud-pattern.webp",
    "color": "#C7BCA6"
  },
  {
    "id": "xian-terracotta-archer-detail",
    "title": "Terracotta Archer Detail",
    "technique": "Photo Abstract Editorial",
    "city": "xian",
    "cityLabel": "Xi’an",
    "cityDisplay": "XI'AN",
    "code": "XA",
    "coordinates": "34.3416° N / 108.9398° E",
    "image": "/assets/editorial/xian/postcard/terracotta-archer-detail.webp",
    "thumb": "/assets/editorial/xian/postcard/thumb/terracotta-archer-detail.webp",
    "color": "#8b342c"
  },
  {
    "id": "xian-terracotta-conservation",
    "title": "Terracotta Conservation",
    "technique": "Minimal Zine Edition",
    "city": "xian",
    "cityLabel": "Xi’an",
    "cityDisplay": "XI'AN",
    "code": "XA",
    "coordinates": "34.3416° N / 108.9398° E",
    "image": "/assets/editorial/xian/postcard/terracotta-conservation.webp",
    "thumb": "/assets/editorial/xian/postcard/thumb/terracotta-conservation.webp",
    "color": "#BCAA91"
  },
  {
    "id": "xian-wild-goose-pagoda-day",
    "title": "Wild Goose Pagoda Day",
    "technique": "Photo Abstract Editorial",
    "city": "xian",
    "cityLabel": "Xi’an",
    "cityDisplay": "XI'AN",
    "code": "XA",
    "coordinates": "34.3416° N / 108.9398° E",
    "image": "/assets/editorial/xian/postcard/wild-goose-pagoda-day.webp",
    "thumb": "/assets/editorial/xian/postcard/thumb/wild-goose-pagoda-day.webp",
    "color": "#453928"
  },
  {
    "id": "xian-wild-goose-pagoda-night",
    "title": "Wild Goose Pagoda Night",
    "technique": "Minimal Zine Edition",
    "city": "xian",
    "cityLabel": "Xi’an",
    "cityDisplay": "XI'AN",
    "code": "XA",
    "coordinates": "34.3416° N / 108.9398° E",
    "image": "/assets/editorial/xian/postcard/wild-goose-pagoda-night.webp",
    "thumb": "/assets/editorial/xian/postcard/thumb/wild-goose-pagoda-night.webp",
    "color": "#60411B"
  },
  {
    "id": "xian-courtyard-lanterns",
    "title": "Courtyard Lanterns",
    "technique": "Photo Abstract Editorial",
    "city": "xian",
    "cityLabel": "Xi’an",
    "cityDisplay": "XI'AN",
    "code": "XA",
    "coordinates": "34.3416° N / 108.9398° E",
    "image": "/assets/editorial/xian/postcard/courtyard-lanterns.webp",
    "thumb": "/assets/editorial/xian/postcard/thumb/courtyard-lanterns.webp",
    "color": "#4F2B21"
  },
  {
    "id": "xian-city-wall-rampart",
    "title": "City Wall Rampart",
    "technique": "Minimal Zine Edition",
    "city": "xian",
    "cityLabel": "Xi’an",
    "cityDisplay": "XI'AN",
    "code": "XA",
    "coordinates": "34.3416° N / 108.9398° E",
    "image": "/assets/editorial/xian/postcard/city-wall-rampart.webp",
    "thumb": "/assets/editorial/xian/postcard/thumb/city-wall-rampart.webp",
    "color": "#978F5E"
  },
  {
    "id": "xian-city-wall-lanterns",
    "title": "City Wall Lanterns",
    "technique": "Photo Abstract Editorial",
    "city": "xian",
    "cityLabel": "Xi’an",
    "cityDisplay": "XI'AN",
    "code": "XA",
    "coordinates": "34.3416° N / 108.9398° E",
    "image": "/assets/editorial/xian/postcard/city-wall-lanterns.webp",
    "thumb": "/assets/editorial/xian/postcard/thumb/city-wall-lanterns.webp",
    "color": "#46392B"
  },
  {
    "id": "xian-night-market",
    "title": "Night Market",
    "technique": "Minimal Zine Edition",
    "city": "xian",
    "cityLabel": "Xi’an",
    "cityDisplay": "XI'AN",
    "code": "XA",
    "coordinates": "34.3416° N / 108.9398° E",
    "image": "/assets/editorial/xian/postcard/night-market.webp",
    "thumb": "/assets/editorial/xian/postcard/thumb/night-market.webp",
    "color": "#252D51"
  },
  {
    "id": "xian-bell-tower-night",
    "title": "Bell Tower Night",
    "technique": "Photo Abstract Editorial",
    "city": "xian",
    "cityLabel": "Xi’an",
    "cityDisplay": "XI'AN",
    "code": "XA",
    "coordinates": "34.3416° N / 108.9398° E",
    "image": "/assets/editorial/xian/postcard/bell-tower-night.webp",
    "thumb": "/assets/editorial/xian/postcard/thumb/bell-tower-night.webp",
    "color": "#2A4349"
  },
  {
    "id": "xian-dragon-lantern-night",
    "title": "Dragon Lantern Night",
    "technique": "Minimal Zine Edition",
    "city": "xian",
    "cityLabel": "Xi’an",
    "cityDisplay": "XI'AN",
    "code": "XA",
    "coordinates": "34.3416° N / 108.9398° E",
    "image": "/assets/editorial/xian/postcard/dragon-lantern-night.webp",
    "thumb": "/assets/editorial/xian/postcard/thumb/dragon-lantern-night.webp",
    "color": "#097BA0"
  },
  {
    "id": "xian-urban-forest",
    "title": "Urban Forest",
    "technique": "Photo Abstract Editorial",
    "city": "xian",
    "cityLabel": "Xi’an",
    "cityDisplay": "XI'AN",
    "code": "XA",
    "coordinates": "34.3416° N / 108.9398° E",
    "image": "/assets/editorial/xian/postcard/urban-forest.webp",
    "thumb": "/assets/editorial/xian/postcard/thumb/urban-forest.webp",
    "color": "#515729"
  },
  {
    "id": "xian-lakeside-pavilion",
    "title": "Lakeside Pavilion",
    "technique": "Minimal Zine Edition",
    "city": "xian",
    "cityLabel": "Xi’an",
    "cityDisplay": "XI'AN",
    "code": "XA",
    "coordinates": "34.3416° N / 108.9398° E",
    "image": "/assets/editorial/xian/postcard/lakeside-pavilion.webp",
    "thumb": "/assets/editorial/xian/postcard/thumb/lakeside-pavilion.webp",
    "color": "#5BACDA"
  },
  {
    "id": "beijing-measured-courtyard",
    "title": "Measured Courtyard",
    "technique": "Photo Abstract Editorial",
    "city": "beijing",
    "cityLabel": "Beijing",
    "cityDisplay": "BEIJING",
    "code": "BJ",
    "coordinates": "39.9042° N / 116.4074° E",
    "image": "/assets/editorial/beijing/postcard/measured-courtyard.webp",
    "thumb": "/assets/editorial/beijing/postcard/thumb/measured-courtyard.webp",
    "color": "#378295"
  },
  {
    "id": "beijing-doorway-at-noon",
    "title": "Doorway at Noon",
    "technique": "Minimal Zine Edition",
    "city": "beijing",
    "cityLabel": "Beijing",
    "cityDisplay": "BEIJING",
    "code": "BJ",
    "coordinates": "39.9042° N / 116.4074° E",
    "image": "/assets/editorial/beijing/postcard/doorway-at-noon.webp",
    "thumb": "/assets/editorial/beijing/postcard/thumb/doorway-at-noon.webp",
    "color": "#967059"
  },
  {
    "id": "beijing-ordinary-velocity",
    "title": "Ordinary Velocity",
    "technique": "Minimal Zine Edition",
    "city": "beijing",
    "cityLabel": "Beijing",
    "cityDisplay": "BEIJING",
    "code": "BJ",
    "coordinates": "39.9042° N / 116.4074° E",
    "image": "/assets/editorial/beijing/postcard/ordinary-velocity.webp",
    "thumb": "/assets/editorial/beijing/postcard/thumb/ordinary-velocity.webp",
    "color": "#B18978"
  },
  {
    "id": "beijing-rings-of-light",
    "title": "Rings of Light",
    "technique": "Photo Abstract Editorial",
    "city": "beijing",
    "cityLabel": "Beijing",
    "cityDisplay": "BEIJING",
    "code": "BJ",
    "coordinates": "39.9042° N / 116.4074° E",
    "image": "/assets/editorial/beijing/postcard/rings-of-light.webp",
    "thumb": "/assets/editorial/beijing/postcard/thumb/rings-of-light.webp",
    "color": "#552F13"
  },
  {
    "id": "beijing-roofs-hold-evening",
    "title": "Roofs Hold Evening",
    "technique": "Photo Abstract Editorial",
    "city": "beijing",
    "cityLabel": "Beijing",
    "cityDisplay": "BEIJING",
    "code": "BJ",
    "coordinates": "39.9042° N / 116.4074° E",
    "image": "/assets/editorial/beijing/postcard/roofs-hold-evening.webp",
    "thumb": "/assets/editorial/beijing/postcard/thumb/roofs-hold-evening.webp",
    "color": "#4E341E"
  },
  {
    "id": "beijing-order-under-sky",
    "title": "Order Under Sky",
    "technique": "Photo Abstract Editorial",
    "city": "beijing",
    "cityLabel": "Beijing",
    "cityDisplay": "BEIJING",
    "code": "BJ",
    "coordinates": "39.9042° N / 116.4074° E",
    "image": "/assets/editorial/beijing/postcard/order-under-sky.webp",
    "thumb": "/assets/editorial/beijing/postcard/thumb/order-under-sky.webp",
    "color": "#026D75"
  },
  {
    "id": "beijing-the-city-bends",
    "title": "The City Bends",
    "technique": "Photo Abstract Editorial",
    "city": "beijing",
    "cityLabel": "Beijing",
    "cityDisplay": "BEIJING",
    "code": "BJ",
    "coordinates": "39.9042° N / 116.4074° E",
    "image": "/assets/editorial/beijing/postcard/the-city-bends.webp",
    "thumb": "/assets/editorial/beijing/postcard/thumb/the-city-bends.webp",
    "color": "#233C51"
  },
  {
    "id": "beijing-storm-over-glass",
    "title": "Storm Over Glass",
    "technique": "Photo Abstract Editorial",
    "city": "beijing",
    "cityLabel": "Beijing",
    "cityDisplay": "BEIJING",
    "code": "BJ",
    "coordinates": "39.9042° N / 116.4074° E",
    "image": "/assets/editorial/beijing/postcard/storm-over-glass.webp",
    "thumb": "/assets/editorial/beijing/postcard/thumb/storm-over-glass.webp",
    "color": "#008700"
  },
  {
    "id": "beijing-ridge-after-ridge",
    "title": "Ridge After Ridge",
    "technique": "Photo Abstract Editorial",
    "city": "beijing",
    "cityLabel": "Beijing",
    "cityDisplay": "BEIJING",
    "code": "BJ",
    "coordinates": "39.9042° N / 116.4074° E",
    "image": "/assets/editorial/beijing/postcard/ridge-after-ridge.webp",
    "thumb": "/assets/editorial/beijing/postcard/thumb/ridge-after-ridge.webp",
    "color": "#494A2D"
  },
  {
    "id": "beijing-rain-keeps-the-street",
    "title": "Rain Keeps the Street",
    "technique": "Photo Abstract Editorial",
    "city": "beijing",
    "cityLabel": "Beijing",
    "cityDisplay": "BEIJING",
    "code": "BJ",
    "coordinates": "39.9042° N / 116.4074° E",
    "image": "/assets/editorial/beijing/postcard/rain-keeps-the-street.webp",
    "thumb": "/assets/editorial/beijing/postcard/thumb/rain-keeps-the-street.webp",
    "color": "#9C6B4F"
  },
  {
    "id": "beijing-the-shop-stays-open",
    "title": "The Shop Stays Open",
    "technique": "Minimal Zine Edition",
    "city": "beijing",
    "cityLabel": "Beijing",
    "cityDisplay": "BEIJING",
    "code": "BJ",
    "coordinates": "39.9042° N / 116.4074° E",
    "image": "/assets/editorial/beijing/postcard/the-shop-stays-open.webp",
    "thumb": "/assets/editorial/beijing/postcard/thumb/the-shop-stays-open.webp",
    "color": "#5A302C"
  },
  {
    "id": "beijing-between-two-chairs",
    "title": "Between Two Chairs",
    "technique": "Minimal Zine Edition",
    "city": "beijing",
    "cityLabel": "Beijing",
    "cityDisplay": "BEIJING",
    "code": "BJ",
    "coordinates": "39.9042° N / 116.4074° E",
    "image": "/assets/editorial/beijing/postcard/between-two-chairs.webp",
    "thumb": "/assets/editorial/beijing/postcard/thumb/between-two-chairs.webp",
    "color": "#2A4E50"
  },
  {
    "id": "beijing-winter-in-sugar",
    "title": "Winter in Sugar",
    "technique": "Minimal Zine Edition",
    "city": "beijing",
    "cityLabel": "Beijing",
    "cityDisplay": "BEIJING",
    "code": "BJ",
    "coordinates": "39.9042° N / 116.4074° E",
    "image": "/assets/editorial/beijing/postcard/winter-in-sugar.webp",
    "thumb": "/assets/editorial/beijing/postcard/thumb/winter-in-sugar.webp",
    "color": "#5A201F"
  },
  {
    "id": "beijing-behind-the-glass",
    "title": "Behind the Glass",
    "technique": "Minimal Zine Edition",
    "city": "beijing",
    "cityLabel": "Beijing",
    "cityDisplay": "BEIJING",
    "code": "BJ",
    "coordinates": "39.9042° N / 116.4074° E",
    "image": "/assets/editorial/beijing/postcard/behind-the-glass.webp",
    "thumb": "/assets/editorial/beijing/postcard/thumb/behind-the-glass.webp",
    "color": "#4E321E"
  },
  {
    "id": "beijing-winter-holds-red",
    "title": "Winter Holds Red",
    "technique": "Minimal Zine Edition",
    "city": "beijing",
    "cityLabel": "Beijing",
    "cityDisplay": "BEIJING",
    "code": "BJ",
    "coordinates": "39.9042° N / 116.4074° E",
    "image": "/assets/editorial/beijing/postcard/winter-holds-red.webp",
    "thumb": "/assets/editorial/beijing/postcard/thumb/winter-holds-red.webp",
    "color": "#a53b2e"
  },
  {
    "id": "beijing-the-square-after-dark",
    "title": "The Square After Dark",
    "technique": "Minimal Zine Edition",
    "city": "beijing",
    "cityLabel": "Beijing",
    "cityDisplay": "BEIJING",
    "code": "BJ",
    "coordinates": "39.9042° N / 116.4074° E",
    "image": "/assets/editorial/beijing/postcard/the-square-after-dark.webp",
    "thumb": "/assets/editorial/beijing/postcard/thumb/the-square-after-dark.webp",
    "color": "#54322D"
  },
  {
    "id": "shanghai-river-in-fog",
    "title": "River in Fog",
    "technique": "Photo Abstract Editorial",
    "city": "shanghai",
    "cityLabel": "Shanghai",
    "cityDisplay": "SHANGHAI",
    "code": "SH",
    "coordinates": "31.2304° N / 121.4737° E",
    "image": "/assets/editorial/shanghai/postcard/river-in-fog.webp",
    "thumb": "/assets/editorial/shanghai/postcard/thumb/river-in-fog.webp",
    "color": "#174c58"
  },
  {
    "id": "shanghai-blue-hour-crossing",
    "title": "Blue Hour Crossing",
    "technique": "Photo Abstract Editorial",
    "city": "shanghai",
    "cityLabel": "Shanghai",
    "cityDisplay": "SHANGHAI",
    "code": "SH",
    "coordinates": "31.2304° N / 121.4737° E",
    "image": "/assets/editorial/shanghai/postcard/blue-hour-crossing.webp",
    "thumb": "/assets/editorial/shanghai/postcard/thumb/blue-hour-crossing.webp",
    "color": "#214A57"
  },
  {
    "id": "shanghai-door-stays-gold",
    "title": "The Door Stays Gold",
    "technique": "Minimal Zine Edition",
    "city": "shanghai",
    "cityLabel": "Shanghai",
    "cityDisplay": "SHANGHAI",
    "code": "SH",
    "coordinates": "31.2304° N / 121.4737° E",
    "image": "/assets/editorial/shanghai/postcard/door-stays-gold.webp",
    "thumb": "/assets/editorial/shanghai/postcard/thumb/door-stays-gold.webp",
    "color": "#324854"
  },
  {
    "id": "shanghai-city-worn-close",
    "title": "The City, Worn Close",
    "technique": "Photo Abstract Editorial",
    "city": "shanghai",
    "cityLabel": "Shanghai",
    "cityDisplay": "SHANGHAI",
    "code": "SH",
    "coordinates": "31.2304° N / 121.4737° E",
    "image": "/assets/editorial/shanghai/postcard/city-worn-close.webp",
    "thumb": "/assets/editorial/shanghai/postcard/thumb/city-worn-close.webp",
    "color": "#555128"
  },
  {
    "id": "shanghai-bund-west-bank",
    "title": "Bund West Bank",
    "technique": "Photo Abstract Editorial",
    "city": "shanghai",
    "cityLabel": "Shanghai",
    "cityDisplay": "SHANGHAI",
    "code": "SH",
    "coordinates": "31.2304° N / 121.4737° E",
    "image": "/assets/editorial/shanghai/postcard/bund-west-bank.webp",
    "thumb": "/assets/editorial/shanghai/postcard/thumb/bund-west-bank.webp",
    "color": "#28452F"
  },
  {
    "id": "shanghai-bund-monochrome",
    "title": "Bund Monochrome",
    "technique": "Minimal Zine Edition",
    "city": "shanghai",
    "cityLabel": "Shanghai",
    "cityDisplay": "SHANGHAI",
    "code": "SH",
    "coordinates": "31.2304° N / 121.4737° E",
    "image": "/assets/editorial/shanghai/postcard/bund-monochrome.webp",
    "thumb": "/assets/editorial/shanghai/postcard/thumb/bund-monochrome.webp",
    "color": "#174c58"
  },
  {
    "id": "shanghai-waterfront-sunset",
    "title": "Waterfront Sunset",
    "technique": "Photo Abstract Editorial",
    "city": "shanghai",
    "cityLabel": "Shanghai",
    "cityDisplay": "SHANGHAI",
    "code": "SH",
    "coordinates": "31.2304° N / 121.4737° E",
    "image": "/assets/editorial/shanghai/postcard/waterfront-sunset.webp",
    "thumb": "/assets/editorial/shanghai/postcard/thumb/waterfront-sunset.webp",
    "color": "#573120"
  },
  {
    "id": "shanghai-people-and-city",
    "title": "People And City",
    "technique": "Minimal Zine Edition",
    "city": "shanghai",
    "cityLabel": "Shanghai",
    "cityDisplay": "SHANGHAI",
    "code": "SH",
    "coordinates": "31.2304° N / 121.4737° E",
    "image": "/assets/editorial/shanghai/postcard/people-and-city.webp",
    "thumb": "/assets/editorial/shanghai/postcard/thumb/people-and-city.webp",
    "color": "#1C344D"
  },
  {
    "id": "shanghai-east-nanjing-road",
    "title": "East Nanjing Road",
    "technique": "Photo Abstract Editorial",
    "city": "shanghai",
    "cityLabel": "Shanghai",
    "cityDisplay": "SHANGHAI",
    "code": "SH",
    "coordinates": "31.2304° N / 121.4737° E",
    "image": "/assets/editorial/shanghai/postcard/east-nanjing-road.webp",
    "thumb": "/assets/editorial/shanghai/postcard/thumb/east-nanjing-road.webp",
    "color": "#D39363"
  },
  {
    "id": "shanghai-morning-lane",
    "title": "Morning Lane",
    "technique": "Minimal Zine Edition",
    "city": "shanghai",
    "cityLabel": "Shanghai",
    "cityDisplay": "SHANGHAI",
    "code": "SH",
    "coordinates": "31.2304° N / 121.4737° E",
    "image": "/assets/editorial/shanghai/postcard/morning-lane.webp",
    "thumb": "/assets/editorial/shanghai/postcard/thumb/morning-lane.webp",
    "color": "#174c58"
  },
  {
    "id": "shanghai-elevator-bridge",
    "title": "Elevator Bridge",
    "technique": "Photo Abstract Editorial",
    "city": "shanghai",
    "cityLabel": "Shanghai",
    "cityDisplay": "SHANGHAI",
    "code": "SH",
    "coordinates": "31.2304° N / 121.4737° E",
    "image": "/assets/editorial/shanghai/postcard/elevator-bridge.webp",
    "thumb": "/assets/editorial/shanghai/postcard/thumb/elevator-bridge.webp",
    "color": "#845634"
  },
  {
    "id": "shanghai-port-road",
    "title": "Port Road",
    "technique": "Minimal Zine Edition",
    "city": "shanghai",
    "cityLabel": "Shanghai",
    "cityDisplay": "SHANGHAI",
    "code": "SH",
    "coordinates": "31.2304° N / 121.4737° E",
    "image": "/assets/editorial/shanghai/postcard/port-road.webp",
    "thumb": "/assets/editorial/shanghai/postcard/thumb/port-road.webp",
    "color": "#2A3D42"
  },
  {
    "id": "shanghai-nanjing-east-crowd",
    "title": "Nanjing East Crowd",
    "technique": "Photo Abstract Editorial",
    "city": "shanghai",
    "cityLabel": "Shanghai",
    "cityDisplay": "SHANGHAI",
    "code": "SH",
    "coordinates": "31.2304° N / 121.4737° E",
    "image": "/assets/editorial/shanghai/postcard/nanjing-east-crowd.webp",
    "thumb": "/assets/editorial/shanghai/postcard/thumb/nanjing-east-crowd.webp",
    "color": "#8F6B5A"
  },
  {
    "id": "shanghai-theatre-curve-ii",
    "title": "Theatre / Curve II",
    "technique": "Minimal Zine Edition",
    "city": "shanghai",
    "cityLabel": "Shanghai",
    "cityDisplay": "SHANGHAI",
    "code": "SH",
    "coordinates": "31.2304° N / 121.4737° E",
    "image": "/assets/editorial/shanghai/postcard/theatre-curve-ii.webp",
    "thumb": "/assets/editorial/shanghai/postcard/thumb/theatre-curve-ii.webp",
    "color": "#174c58"
  },
  {
    "id": "shanghai-theatre-curve-i",
    "title": "Theatre / Curve I",
    "technique": "Photo Abstract Editorial",
    "city": "shanghai",
    "cityLabel": "Shanghai",
    "cityDisplay": "SHANGHAI",
    "code": "SH",
    "coordinates": "31.2304° N / 121.4737° E",
    "image": "/assets/editorial/shanghai/postcard/theatre-curve-i.webp",
    "thumb": "/assets/editorial/shanghai/postcard/thumb/theatre-curve-i.webp",
    "color": "#174c58"
  },
  {
    "id": "shanghai-shanghai-art",
    "title": "Shanghai Art",
    "technique": "Minimal Zine Edition",
    "city": "shanghai",
    "cityLabel": "Shanghai",
    "cityDisplay": "SHANGHAI",
    "code": "SH",
    "coordinates": "31.2304° N / 121.4737° E",
    "image": "/assets/editorial/shanghai/postcard/shanghai-art.webp",
    "thumb": "/assets/editorial/shanghai/postcard/thumb/shanghai-art.webp",
    "color": "#5A442A"
  },
  {
    "id": "shanghai-ship-on-land",
    "title": "Ship On Land",
    "technique": "Photo Abstract Editorial",
    "city": "shanghai",
    "cityLabel": "Shanghai",
    "cityDisplay": "SHANGHAI",
    "code": "SH",
    "coordinates": "31.2304° N / 121.4737° E",
    "image": "/assets/editorial/shanghai/postcard/ship-on-land.webp",
    "thumb": "/assets/editorial/shanghai/postcard/thumb/ship-on-land.webp",
    "color": "#CE987F"
  },
  {
    "id": "shanghai-apple-jingan",
    "title": "Apple Jingan",
    "technique": "Minimal Zine Edition",
    "city": "shanghai",
    "cityLabel": "Shanghai",
    "cityDisplay": "SHANGHAI",
    "code": "SH",
    "coordinates": "31.2304° N / 121.4737° E",
    "image": "/assets/editorial/shanghai/postcard/apple-jingan.webp",
    "thumb": "/assets/editorial/shanghai/postcard/thumb/apple-jingan.webp",
    "color": "#174c58"
  },
  {
    "id": "shanghai-ruijin-road",
    "title": "Ruijin Road",
    "technique": "Photo Abstract Editorial",
    "city": "shanghai",
    "cityLabel": "Shanghai",
    "cityDisplay": "SHANGHAI",
    "code": "SH",
    "coordinates": "31.2304° N / 121.4737° E",
    "image": "/assets/editorial/shanghai/postcard/ruijin-road.webp",
    "thumb": "/assets/editorial/shanghai/postcard/thumb/ruijin-road.webp",
    "color": "#423B27"
  },
  {
    "id": "shanghai-waldorf-facade",
    "title": "Waldorf Facade",
    "technique": "Minimal Zine Edition",
    "city": "shanghai",
    "cityLabel": "Shanghai",
    "cityDisplay": "SHANGHAI",
    "code": "SH",
    "coordinates": "31.2304° N / 121.4737° E",
    "image": "/assets/editorial/shanghai/postcard/waldorf-facade.webp",
    "thumb": "/assets/editorial/shanghai/postcard/thumb/waldorf-facade.webp",
    "color": "#7EADC3"
  },
  {
    "id": "shanghai-yuanmingyuan-road",
    "title": "Yuanmingyuan Road",
    "technique": "Photo Abstract Editorial",
    "city": "shanghai",
    "cityLabel": "Shanghai",
    "cityDisplay": "SHANGHAI",
    "code": "SH",
    "coordinates": "31.2304° N / 121.4737° E",
    "image": "/assets/editorial/shanghai/postcard/yuanmingyuan-road.webp",
    "thumb": "/assets/editorial/shanghai/postcard/thumb/yuanmingyuan-road.webp",
    "color": "#BB9571"
  },
  {
    "id": "shanghai-qipao-shop",
    "title": "Qipao Shop",
    "technique": "Minimal Zine Edition",
    "city": "shanghai",
    "cityLabel": "Shanghai",
    "cityDisplay": "SHANGHAI",
    "code": "SH",
    "coordinates": "31.2304° N / 121.4737° E",
    "image": "/assets/editorial/shanghai/postcard/qipao-shop.webp",
    "thumb": "/assets/editorial/shanghai/postcard/thumb/qipao-shop.webp",
    "color": "#9E6859"
  },
  {
    "id": "shanghai-qipao-shadow",
    "title": "Qipao Shadow",
    "technique": "Photo Abstract Editorial",
    "city": "shanghai",
    "cityLabel": "Shanghai",
    "cityDisplay": "SHANGHAI",
    "code": "SH",
    "coordinates": "31.2304° N / 121.4737° E",
    "image": "/assets/editorial/shanghai/postcard/qipao-shadow.webp",
    "thumb": "/assets/editorial/shanghai/postcard/thumb/qipao-shadow.webp",
    "color": "#5C572D"
  },
  {
    "id": "shanghai-qipao-alley",
    "title": "Qipao Alley",
    "technique": "Minimal Zine Edition",
    "city": "shanghai",
    "cityLabel": "Shanghai",
    "cityDisplay": "SHANGHAI",
    "code": "SH",
    "coordinates": "31.2304° N / 121.4737° E",
    "image": "/assets/editorial/shanghai/postcard/qipao-alley.webp",
    "thumb": "/assets/editorial/shanghai/postcard/thumb/qipao-alley.webp",
    "color": "#1C3050"
  },
  {
    "id": "shanghai-romantic-waterfront",
    "title": "Romantic Waterfront",
    "technique": "Photo Abstract Editorial",
    "city": "shanghai",
    "cityLabel": "Shanghai",
    "cityDisplay": "SHANGHAI",
    "code": "SH",
    "coordinates": "31.2304° N / 121.4737° E",
    "image": "/assets/editorial/shanghai/postcard/romantic-waterfront.webp",
    "thumb": "/assets/editorial/shanghai/postcard/thumb/romantic-waterfront.webp",
    "color": "#5F8798"
  },
  {
    "id": "shanghai-night-street",
    "title": "Night Street",
    "technique": "Minimal Zine Edition",
    "city": "shanghai",
    "cityLabel": "Shanghai",
    "cityDisplay": "SHANGHAI",
    "code": "SH",
    "coordinates": "31.2304° N / 121.4737° E",
    "image": "/assets/editorial/shanghai/postcard/night-street.webp",
    "thumb": "/assets/editorial/shanghai/postcard/thumb/night-street.webp",
    "color": "#2B4A53"
  },
  {
    "id": "shanghai-xiaolongbao",
    "title": "Xiaolongbao",
    "technique": "Photo Abstract Editorial",
    "city": "shanghai",
    "cityLabel": "Shanghai",
    "cityDisplay": "SHANGHAI",
    "code": "SH",
    "coordinates": "31.2304° N / 121.4737° E",
    "image": "/assets/editorial/shanghai/postcard/xiaolongbao.webp",
    "thumb": "/assets/editorial/shanghai/postcard/thumb/xiaolongbao.webp",
    "color": "#324152"
  }
]);
