(()=>{
const content=document.getElementById('search003-content');
const parts=(content?.dataset.parts||'').split(',').filter(Boolean);
function mountEditorialPhotos(){
  if(!document.querySelector('link[data-s003-editorial]')){const l=document.createElement('link');l.rel='stylesheet';l.href='/research/love-by-the-hour/search003-editorial.css?v=20260829a';l.dataset.s003Editorial='';document.head.appendChild(l)}
  const hero=document.querySelector('.research003-hero');
  if(hero&&!hero.querySelector('[data-editorial-cover]'))hero.insertAdjacentHTML('beforeend',`<figure class="s003-editorial-photo s003-editorial-photo--cover" data-editorial-cover><img src="/research/love-by-the-hour/media/cover-crossing.svg" width="1000" height="646" alt="A lone pedestrian crossing a large striped road intersection seen from above" fetchpriority="high" decoding="async"><figcaption><span>Editorial photograph · Cover</span><span>wal_172619 / Pixabay</span></figcaption></figure>`);
  if(!content)return;
  const intro=[...content.querySelectorAll('p')].find(p=>p.textContent.trim().startsWith('This is why gaming companionship cannot be adequately understood as a narrow service category.'));
  if(intro&&!content.querySelector('[data-editorial-traffic]'))intro.insertAdjacentHTML('beforebegin',`<figure class="s003-editorial-photo s003-editorial-photo--wide" data-editorial-traffic><img src="/research/love-by-the-hour/media/city-traffic.svg" width="1000" height="626" alt="Pedestrians crossing a busy multilane city road among cars and vans" loading="lazy" decoding="async"><figcaption><span>Editorial photograph · Section art, not study evidence</span><span>wal_172619 / Pixabay</span></figcaption></figure>`);
  const tenderness=document.getElementById('selling-tenderness');
  if(tenderness&&!content.querySelector('[data-editorial-runway]'))tenderness.insertAdjacentHTML('afterend',`<figure class="s003-editorial-photo s003-editorial-photo--wide" data-editorial-runway><img src="/research/love-by-the-hour/media/runway-lines.svg" width="1000" height="667" alt="A person in striped trousers walking across a black-and-white illuminated runway" loading="lazy" decoding="async"><figcaption><span>Editorial photograph · Section art, not study evidence</span><span>Anewbist / Pixabay</span></figcaption></figure>`);
  const labor=document.getElementById('when-intimacy-becomes-labor');
  if(labor&&!content.querySelector('[data-editorial-blur]'))labor.insertAdjacentHTML('afterend',`<figure class="s003-editorial-photo s003-editorial-photo--wide s003-editorial-photo--dark" data-editorial-blur><img src="/research/love-by-the-hour/media/blur-crossing.svg" width="1000" height="667" alt="A blurred black-and-white figure moving across a striped pedestrian crossing at night" loading="lazy" decoding="async"><figcaption><span>Editorial photograph · Section art, not study evidence</span><span>Plato Terentev / Pexels</span></figcaption></figure>`);
}
async function loadPaper(){if(!content||!parts.length){mountEditorialPhotos();initVisuals();return;}try{const html=await Promise.all(parts.map(async u=>{const r=await fetch(u);if(!r.ok)throw new Error(`${r.status} ${u}`);return r.text()}));content.innerHTML=html.join('');mountEditorialPhotos();initVisuals();if(location.hash)requestAnimationFrame(()=>document.getElementById(location.hash.slice(1))?.scrollIntoView());}catch(e){content.innerHTML=`<div class="s003-load-error"><strong>Working paper failed to load.</strong><br>${String(e.message||e)}</div>`}}
const DATA=window.SEARCH003_DATA;
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)], esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const labels={personal:'Lightweight individual',studio:'Studio',club:'Guild / club / back office',hybrid:'Studio + MCN',unknown:'Unknown'}, colors={personal:'#64748b',studio:'#d97706',club:'#0d9488',hybrid:'#8b5cf6',unknown:'#aaa'};
function initVisuals(){
const price=$('[data-s003-price]');if(price){let unit='diamonds';price.innerHTML='<div class="s003-controls"><button type="button" data-u="diamonds" aria-pressed="true">Diamonds</button><button type="button" data-u="rmb" aria-pressed="false">Verified RMB</button></div><div data-bars></div>';const bars=$('[data-bars]',price);const draw=()=>{const rows=DATA.pricing.filter(x=>unit==='diamonds'||x.rmb!=null),mx=Math.max(...rows.map(x=>unit==='diamonds'?x.diamonds:x.rmb));bars.innerHTML=rows.map(x=>{const v=unit==='diamonds'?x.diamonds:x.rmb;return `<div class="s003-price-row"><span>${esc(x.item)}</span><i><b style="width:${v/mx*100}%"></b></i><strong>${v}${unit==='diamonds'?' diamonds':' RMB'}</strong><small>${esc(x.evidence)}</small></div>`}).join('')};$$('[data-u]',price).forEach(b=>b.onclick=()=>{unit=b.dataset.u;$$('[data-u]',price).forEach(x=>x.setAttribute('aria-pressed',x===b));draw()});draw()}
const org=$('[data-s003-org]');if(org){const sizes=[...new Set(DATA.accounts.map(a=>a.size))];org.innerHTML=`<div class="s003-controls"><label>Follower scale <select data-os><option value="all">All</option>${sizes.map(s=>`<option>${esc(s)}</option>`).join('')}</select></label><label>Organization <select data-ot><option value="all">All</option>${DATA.orgOrder.map(o=>`<option value="${o}">${esc(labels[o])}</option>`).join('')}</select></label></div><div class="s003-org-table" data-otable></div><div class="s003-mini-note" data-onote>Select a row for evidence.</div>`;const os=$('[data-os]',org),ot=$('[data-ot]',org),tb=$('[data-otable]',org),note=$('[data-onote]',org);const draw=()=>{const a=DATA.accounts.filter(x=>(os.value==='all'||x.size===os.value)&&(ot.value==='all'||x.org===ot.value));tb.innerHTML='<div class="h n">Account</div><div class="h">Followers</div><div class="h">Organization</div><div class="h">Monetization</div><div class="h">Acquisition route</div>'+a.map(x=>`<button type="button" class="n" data-oid="${x.id}">${esc(x.name)}</button><div>${esc(x.followersLabel)}</div><div><span class="s003-badge ${x.org}">${esc(labels[x.org])}</span></div><div>${esc(x.monetization)}</div><div>${esc(x.acquisition)}</div>`).join('');$$('[data-oid]',tb).forEach(n=>n.onclick=()=>{const x=DATA.accounts.find(a=>a.id===n.dataset.oid);note.innerHTML=`<strong>${esc(x.name)}</strong> · ${esc(x.orgLabel)} · Evidence ${esc(x.evidence)}`})};os.onchange=draw;ot.onchange=draw;draw()}
const tl=$('[data-s003-timeline]');if(tl){const total=267;tl.innerHTML='<div class="s003-dark-rail" data-rail></div><div class="s003-time-labels"><span>00:00</span><span>01:00</span><span>02:00</span><span>03:00</span><span>04:00</span><span>04:27</span></div><div class="s003-event-grid" data-events></div><div class="s003-dark-detail" data-ed></div>';const rail=$('[data-rail]',tl),ev=$('[data-events]',tl),de=$('[data-ed]',tl);DATA.timeline.slice(0,2).forEach(e=>{const b=document.createElement('button');b.type='button';b.className='s003-dark-block '+(e.kind==='conflict'?'abuse':'gift');b.style.left=e.start/total*100+'%';b.style.width=Math.max(2,(e.end-e.start)/total*100)+'%';b.dataset.e=e.id;rail.appendChild(b)});ev.innerHTML=DATA.timeline.map(e=>`<button type="button" class="s003-event-card" data-e="${e.id}"><b>${esc(e.label)}</b><small>${esc(e.time)} · ${esc(e.evidence)}</small></button>`).join('');const sel=id=>{const e=DATA.timeline.find(x=>x.id===id);$$('[data-e]',tl).forEach(x=>x.classList.toggle('is-selected',x.dataset.e===id));de.innerHTML=`<strong>${esc(e.label)}</strong><br>${esc(e.detail)}<div style="margin-top:8px;font:10px ui-monospace">Codes ${esc(e.codes)} · ${esc(e.evidence)}</div>`};$$('[data-e]',tl).forEach(x=>x.onclick=()=>sel(x.dataset.e));sel('EP002')}
const paths=$('[data-s003-paths]');if(paths)paths.innerHTML='<div class="s003-paths">'+DATA.paths.map(p=>`<article class="s003-path"><header><b>${esc(p.title)}</b><small>${esc(p.evidence)}</small></header><div class="s003-path-row">${p.stages.map((s,i)=>`${i?'<span class="s003-arrow">→</span>':''}<div class="s003-stage">${esc(s)}</div>`).join('')}</div><footer>Observed examples: ${p.accounts.map(esc).join(', ')}</footer></article>`).join('')+'</div>';
const sc=$('[data-s003-scatter]');if(sc){const dat=DATA.accounts.filter(a=>a.followers&&a.members);sc.innerHTML='<div class="s003-scatter-legend">'+DATA.orgOrder.filter(o=>o!=='unknown').map(o=>`<span><i style="background:${colors[o]}"></i>${esc(labels[o])}</span>`).join('')+'</div><div class="s003-viz-grid"><div class="s003-chart" data-chart></div><aside class="s003-panel" data-det><h5>Observed membership is highly uneven</h5><p>Click a point. “Total joined” may be cumulative; no live paid conversion rate is calculated.</p></aside></div>';const ch=$('[data-chart]',sc),det=$('[data-det]',sc);const lg=v=>Math.log(v)/Math.LN10,W=680,H=390,p={l:58,r:18,t:18,b:54},xmin=Math.min(...dat.map(a=>lg(a.followers)))-.12,xmax=Math.max(...dat.map(a=>lg(a.followers)))+.12,ymin=Math.min(...dat.map(a=>lg(a.members)))-.16,ymax=Math.max(...dat.map(a=>lg(a.members)))+.16,x=v=>p.l+(lg(v)-xmin)/(xmax-xmin)*(W-p.l-p.r),y=v=>H-p.b-(lg(v)-ymin)/(ymax-ymin)*(H-p.t-p.b);let s=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Followers versus displayed membership joins">`;[1e4,1e5,1e6,1e7].forEach(v=>{const xx=x(v);s+=`<line class="s003-axis" x1="${xx}" x2="${xx}" y1="${p.t}" y2="${H-p.b}"/><text class="s003-tick" x="${xx}" y="${H-p.b+20}" text-anchor="middle">${v>=1e6?v/1e6+'m':v/1e3+'k'}</text>`});[10,100,1000,10000].forEach(v=>{const yy=y(v);s+=`<line class="s003-axis" x1="${p.l}" x2="${W-p.r}" y1="${yy}" y2="${yy}"/><text class="s003-tick" x="${p.l-8}" y="${yy+4}" text-anchor="end">${v>=1000?v/1000+'k':v}</text>`});dat.forEach(a=>s+=`<circle class="s003-point" data-id="${a.id}" cx="${x(a.followers)}" cy="${y(a.members)}" r="6" fill="${colors[a.org]}"/>`);ch.innerHTML=s+'</svg>';$$('[data-id]',ch).forEach(pt=>pt.onclick=()=>{const a=DATA.accounts.find(x=>x.id===pt.dataset.id);det.innerHTML=`<h5>${esc(a.name)}</h5><dl class="s003-kv"><dt>Followers</dt><dd>${esc(a.followersLabel)}</dd><dt>Members</dt><dd>${esc(a.membersLabel)}</dd><dt>Organization</dt><dd>${esc(a.orgLabel)}</dd><dt>Evidence</dt><dd>${esc(a.evidence)}</dd></dl>`})}
}
mountEditorialPhotos();
loadPaper();
})();