const stream=document.querySelector("[data-radar-stream]");const rail=document.querySelector("[data-radar-time-rail]");const status=document.querySelector("[data-radar-status]");const filters=[...document.querySelectorAll("[data-radar-filter]")];const dialog=document.querySelector("[data-radar-dialog]");const closeDialog=document.querySelector("[data-radar-close]");let signals=[];let activeFilter=new URL(location.href).searchParams.get("state")||"all";let returnFocus;
const escapeHtml=(value="")=>String(value).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replaceAll(String.fromCharCode(34),"&quot;").replaceAll(String.fromCharCode(39),"&#39;");
const safeUrl=(value)=>{try{const url=new URL(value,location.origin);return ["http:","https:"].includes(url.protocol)?url.href:"#"}catch{return"#"}};
const dateLabel=(value)=>new Intl.DateTimeFormat("en",{month:"short",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false,timeZone:"UTC"}).format(new Date(value));
function validate(data){if(data?.version!=="1.0"||!Array.isArray(data.signals))throw new Error("Unsupported Radar data");const states=new Set(["Signal","Brief","Lead","Archive"]);for(const item of data.signals){if(!item.id||!states.has(item.state)||!item.headline||!item.summary||!item.context||!Date.parse(item.updatedAt)||!Array.isArray(item.coverage)||!item.coverage.length)throw new Error(`Invalid signal: ${item.id||"unknown"}`)}return data.signals.sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt))}
function row(item,index){return `<article class="radar-row" data-radar-row data-id="${escapeHtml(item.id)}" data-state="${item.state}" style="--row:${index}"><div class="radar-row__meta"><span class="radar-row__state">${item.state}</span><span>${escapeHtml(item.topic)}<br>${escapeHtml(item.geography)}</span></div><div><h2>${escapeHtml(item.headline)}</h2><p class="radar-row__summary">${escapeHtml(item.summary)}</p></div><div class="radar-row__side"><time datetime="${item.updatedAt}">Updated ${dateLabel(item.updatedAt)} UTC</time><button class="radar-row__evidence" type="button" data-radar-evidence="${escapeHtml(item.id)}">${item.coverage.length} source${item.coverage.length===1?"":"s"} / evidence</button></div></article>`}
function render(){stream.innerHTML=signals.map(row).join("");rail.innerHTML=signals.map((item)=>`<li data-radar-time="${escapeHtml(item.id)}">${dateLabel(item.updatedAt)}<br>${escapeHtml(item.state)}</li>`).join("");applyFilter(activeFilter,false);observeRows();document.documentElement.dataset.radarReady="true"}
function applyFilter(value,animate=true){activeFilter=["Signal","Brief","Lead","Archive"].includes(value)?value:"all";const rows=[...document.querySelectorAll("[data-radar-row]")];if(animate)rows.forEach((node)=>node.classList.add("is-filtering"));setTimeout(()=>{let visible=0;rows.forEach((node)=>{const show=activeFilter==="all"||node.dataset.state===activeFilter;node.hidden=!show;if(show)visible+=1;node.classList.remove("is-filtering")});filters.forEach((button)=>button.setAttribute("aria-pressed",String(button.dataset.radarFilter===activeFilter)));status.textContent=`${visible} verified ${visible===1?"entry":"entries"} / ${activeFilter}`;document.documentElement.dataset.radarState=activeFilter.toLowerCase();const url=new URL(location.href);if(activeFilter==="all")url.searchParams.delete("state");else url.searchParams.set("state",activeFilter);history.replaceState({},"",url)},animate?160:0)}
function openEvidence(id,trigger){const item=signals.find((entry)=>entry.id===id);if(!item)return;returnFocus=trigger;dialog.querySelector("[data-radar-dialog-state]").textContent=`${item.state} / ${item.topic} / ${item.geography}`;dialog.querySelector("[data-radar-dialog-title]").textContent=item.headline;dialog.querySelector("[data-radar-dialog-context]").textContent=item.context;dialog.querySelector("[data-radar-dialog-sources]").innerHTML=item.coverage.map((source)=>`<li><span>${escapeHtml(source.outlet)}</span><a href="${safeUrl(source.url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(source.title)} ↗</a></li>`).join("");dialog.showModal();dialog.querySelector("[data-radar-dialog-title]").focus();window.galokTrack?.("radar_evidence_open",{signal_id:item.id,state:item.state})}
function observeRows(){if(!("IntersectionObserver"in window))return;const observer=new IntersectionObserver((entries)=>entries.forEach((entry)=>{if(!entry.isIntersecting)return;document.querySelectorAll("[data-radar-time]").forEach((node)=>node.classList.toggle("is-current",node.dataset.radarTime===entry.target.dataset.id))}),{rootMargin:"-25% 0px -60%",threshold:.1});document.querySelectorAll("[data-radar-row]").forEach((node)=>observer.observe(node))}
filters.forEach((button)=>button.addEventListener("click",()=>applyFilter(button.dataset.radarFilter)));stream.addEventListener("click",(event)=>{const trigger=event.target.closest("[data-radar-evidence]");if(trigger)openEvidence(trigger.dataset.radarEvidence,trigger)});closeDialog.addEventListener("click",()=>dialog.close());dialog.addEventListener("close",()=>returnFocus?.focus());dialog.addEventListener("click",(event)=>{if(event.target===dialog)dialog.close()});
try{const response=await fetch("/radar/signals.json",{cache:"no-cache"});if(!response.ok)throw new Error(`Radar returned ${response.status}`);signals=validate(await response.json());render()}catch(error){console.error(error);status.textContent="Verified snapshot unavailable. Please return shortly.";stream.innerHTML='<p class="radar-error">The signal ledger could not be loaded.</p>'}
